name: Long Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - name: Create example files
        run: |
          echo "foo" > input.txt # create an example file
          date +%s > report.txt
      - uses: docker://pandoc/core:2.9
        with:
          args: >- # allows you to break string into multiple lines
            --standalone
            --output=index.html
            input.txt
      - uses: actions/checkout@v3
#      - name: Commit output
#        run: |
#          ls ${{ github.workspace }}
#          echo "${{ steps.files_list.outputs.files }}"
#          git add ${{ steps.files_list.outputs.files }}
#          git config --global user.name 'Your Name'
#          git config --global user.email 'your-username@users.noreply.github.com'
#          git commit -am "Automated push"
#          git push
#      - name: Create report file
#        run: date +%s > report.txt
      - name: Commit report
        run: |
          ls ${{ github.workspace }}
          git add report.txt
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          git commit -am "Automated report"
          git push